### ISSUE TITLE
Falsches Veröffentlichungsdatum

### ISSUE THREAD

**Issue by NikeNovak** [symetics/reactjs.de#13]
reactjs.de/_posts/2015-06-30-react-tutorial-deutsch/2015-06-30-react-tutorial-deutsch.md

Einer Ihrer Artikel hat ein Veröffentlichungsdatum, was in der Zukunft liegt.

![image](https://user-images.githubusercontent.com/25428290/50589640-bb76a700-0e87-11e9-9f60-a93318bc9e3f.png)

Freundliche Grüße
Viktoria Heise

**Comment by robinboehm** [comment]
Vielen Dank!
Hab es grad gefixt mit c011e7fad46f46ddbd0687366a5fc6ebb1e76fbe
